-- ============================================
-- SCRIPT COWORKINGDB
-- BLOQUE OPCIONAL: BORRAR TODO
-- ============================================

DROP TABLE BITACORA_CAMBIOS CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE RESERVA_SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE ESTADOS CASCADE CONSTRAINTS;
DROP TABLE SALAS CASCADE CONSTRAINTS;
DROP TABLE TIPO_SALA CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ROLES CASCADE CONSTRAINTS;
DROP TABLE PISO CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO CASCADE CONSTRAINTS;


-- ============================================
-- CREACIÓN DE TABLAS
-- ============================================

CREATE TABLE EDIFICIO (
    ID_EDIFICIO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_EDIFICIO  VARCHAR2(100) NOT NULL,
    DIRECCION        VARCHAR2(255)
);

CREATE TABLE PISO (
    ID_PISO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_PISO  NUMBER NOT NULL,
    ID_EDIFICIO  NUMBER NOT NULL,
    CONSTRAINT FK_PISO_EDIFICIO
        FOREIGN KEY (ID_EDIFICIO)
        REFERENCES EDIFICIO(ID_EDIFICIO)
        ON DELETE CASCADE
);

CREATE TABLE ROLES (
    ID_ROL           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_ROL  VARCHAR2(50) NOT NULL
);

CREATE TABLE USUARIOS (
    ID_USUARIO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE           VARCHAR2(100) NOT NULL,
    APELLIDO_1       VARCHAR2(100) NOT NULL,
    APELLIDO_2       VARCHAR2(100) NOT NULL,
    CORREO           VARCHAR2(100) UNIQUE NOT NULL,
    TELEFONO         VARCHAR2(20),
    CONTRASENA_HASH  VARCHAR2(255) NOT NULL,
    ID_ROL           NUMBER,
    CONSTRAINT FK_USUARIO_ROL
        FOREIGN KEY (ID_ROL)
        REFERENCES ROLES(ID_ROL)
        ON DELETE SET NULL
);

CREATE TABLE TIPO_SALA (
    ID_TIPO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_TIPO  VARCHAR2(50) NOT NULL
);

CREATE TABLE SALAS (
    ID_SALA      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_SALA  VARCHAR2(100) NOT NULL,
    CAPACIDAD    NUMBER NOT NULL,
    PRECIO_HORA  NUMBER(10,2) NOT NULL,
    ID_TIPO      NUMBER,
    ID_PISO      NUMBER,
    CONSTRAINT FK_SALA_TIPO
        FOREIGN KEY (ID_TIPO)
        REFERENCES TIPO_SALA(ID_TIPO)
        ON DELETE SET NULL,
    CONSTRAINT FK_SALA_PISO
        FOREIGN KEY (ID_PISO)
        REFERENCES PISO(ID_PISO)
        ON DELETE SET NULL
);

CREATE TABLE ESTADOS (
    ID_ESTADO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ESTADO  VARCHAR2(50) NOT NULL
);

CREATE TABLE RESERVAS (
    ID_RESERVA   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO   NUMBER NOT NULL,
    ID_SALA      NUMBER NOT NULL,
    ID_ESTADO    NUMBER NOT NULL,
    FECHA        DATE NOT NULL,
    HORA_INICIO  TIMESTAMP NOT NULL,
    HORA_FIN     TIMESTAMP NOT NULL,
    COSTO_TOTAL  NUMBER(12,2),
    CONSTRAINT FK_RESERVA_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_RESERVA_SALA
        FOREIGN KEY (ID_SALA)
        REFERENCES SALAS(ID_SALA),
    CONSTRAINT FK_RESERVA_ESTADO
        FOREIGN KEY (ID_ESTADO)
        REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE SERVICIOS (
    ID_SERVICIO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_SERVICIO   VARCHAR2(100) NOT NULL,
    PRECIO_ADICIONAL  NUMBER(10,2) NOT NULL
);

CREATE TABLE RESERVA_SERVICIOS (
    ID_RESERVA   NUMBER NOT NULL,
    ID_SERVICIO  NUMBER NOT NULL,
    CANTIDAD     NUMBER DEFAULT 1,
    PRIMARY KEY (ID_RESERVA, ID_SERVICIO),
    CONSTRAINT FK_RS_RESERVA
        FOREIGN KEY (ID_RESERVA)
        REFERENCES RESERVAS(ID_RESERVA)
        ON DELETE CASCADE,
    CONSTRAINT FK_RS_SERVICIO
        FOREIGN KEY (ID_SERVICIO)
        REFERENCES SERVICIOS(ID_SERVICIO)
);

CREATE TABLE PAGOS (
    ID_PAGO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_RESERVA   NUMBER NOT NULL,
    MONTO_TOTAL  NUMBER(10,2) NOT NULL,
    FECHA_PAGO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    METODO_PAGO  VARCHAR2(50),
    CONSTRAINT FK_PAGO_RESERVA
        FOREIGN KEY (ID_RESERVA)
        REFERENCES RESERVAS(ID_RESERVA)
);

CREATE TABLE BITACORA_CAMBIOS (
    ID_LOG               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_RESERVA           NUMBER,
    ID_ESTADO_ANTERIOR   NUMBER,
    ID_ESTADO_NUEVO      NUMBER,
    FECHA_CAMBIO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BITACORA_RESERVA
        FOREIGN KEY (ID_RESERVA)
        REFERENCES RESERVAS(ID_RESERVA)
        ON DELETE CASCADE,
    CONSTRAINT FK_BITACORA_ESTADO_ANT
        FOREIGN KEY (ID_ESTADO_ANTERIOR)
        REFERENCES ESTADOS(ID_ESTADO),
    CONSTRAINT FK_BITACORA_ESTADO_NUE
        FOREIGN KEY (ID_ESTADO_NUEVO)
        REFERENCES ESTADOS(ID_ESTADO)
);

COMMIT;
-- ============================================
-- INSERCIÓN DE DATOS
-- ============================================

INSERT INTO EDIFICIO (NOMBRE_EDIFICIO, DIRECCION)
VALUES ('Coworking Central', 'San Jose, Costa Rica');

INSERT INTO EDIFICIO (NOMBRE_EDIFICIO, DIRECCION)
VALUES ('Coworking Escazu', 'Escazu, San Jose');

INSERT INTO PISO (NUMERO_PISO, ID_EDIFICIO) VALUES (1, 1);
INSERT INTO PISO (NUMERO_PISO, ID_EDIFICIO) VALUES (2, 1);
INSERT INTO PISO (NUMERO_PISO, ID_EDIFICIO) VALUES (1, 2);

INSERT INTO ROLES (DESCRIPCION_ROL) VALUES ('Administrador');
INSERT INTO ROLES (DESCRIPCION_ROL) VALUES ('Cliente');
INSERT INTO ROLES (DESCRIPCION_ROL) VALUES ('Recepcionista');

INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL)
VALUES ('Flor', 'Martinez', 'Garcia', 'flor@correo.com', '8888-1111', 'hash123', 1);

INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL)
VALUES ('Ana', 'Lopez', 'Sanchez', 'ana@correo.com', '8888-2222', 'hash456', 2);

INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL)
VALUES ('Carlos', 'Perez', 'Mora', 'carlos@correo.com', '8888-3333', 'hash789', 3);

-- USUARIOS EXTRA
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Alhana', 'Diaz', 'Aguirre', 'alhana@correo.com', '8888-4444', 'hash132', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Stephanie', 'Brenes', 'Araya', 'brenes@correo.com', '8888-5555', 'hash856', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Carlos', 'Gutierrez', 'Quiros', 'gutierrez@correo.com', '8888-6666', 'hash098', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Sandra', 'Rojas', 'Brenes', 'sandra@correo.com', '8877-1234', 'hash139', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Stephanie', 'Brenes', 'Dobles', 'dobles@correo.com', '8877-2345', 'hash176', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Jose', 'Hernandez', 'Perez', 'hernandez@correo.com', '8877-3456', 'hash086', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Martha', 'Fonseca', 'Artavia', 'martha@correo.com', '8877-4567', 'hash443', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Manuel', 'Cruz', 'Cordoba', 'cruz@correo.com', '8877-5678', 'hash406', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Alejandro', 'Leiva', 'Quiros', 'quiros@correo.com', '8877-5679', 'hash998', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Christian', 'Marin', 'Hernandez', 'christian@correo.com', '8877-6789', 'hash566', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Roberto', 'Brenes', 'Araya', 'roberto@correo.com', '8877-7890', 'hash444', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Marco', 'Perez', 'Ramirez', 'marco@correo.com', '8788-1122', 'hash009', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Emilce', 'Romero', 'Martinez', 'emilce@correo.com', '8788-2233', 'hash223', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('David', 'Araya', 'Figueres', 'david@correo.com', '8788-3344', 'hash445', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Marvin', 'Fernandez', 'Robles', 'marvin@correo.com', '8788-4455', 'hash454', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Kevin', 'Abarca', 'Coto', 'coto@correo.com', '8788-5566', 'hash109', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Naomy', 'Alvarado', 'Calderon', 'naomy@correo.com', '8788-6677', 'hash450', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Jimena', 'Mata', 'Barrantes', 'jimena@correo.com', '8788-7788', 'hash012', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Tamara', 'Ramos', 'Morales', 'tamara1@correo.com', '8788-8899', 'hash165', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Myriam', 'Aguirre', 'Chavarria', 'tamara2@correo.com', '8765-8899', 'hash165', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Catalina', 'Navarro', 'Marin', 'tamara3@correo.com', '8766-8899', 'hash887', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Patricia', 'Valencia', 'Mendoza', 'patri@correo.com', '8767-8899', 'hash889', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Armando', 'Gonzales', 'Calderon', 'armando@correo.com', '8761-8899', 'hash656', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Daniel', 'Hernandez', 'Mena', 'danielh@correo.com', '8762-8899', 'hash516', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Mario', 'Delgado', 'Lopez', 'mario@correo.com', '8761-8763', 'hash657', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Marcela', 'Gamboa', 'Ulate', 'marcela@correo.com', '8763-8899', 'hash560', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Pamela', 'Aguirre', 'Brenes', 'pamela@correo.com', '8764-8899', 'hash756', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Nathalie', 'Perez', 'Mora', 'nathalie@correo.com', '8765-8899', 'hash856', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Dayanna', 'Hernandez', 'Ulate', 'dayanna@correo.com', '8766-8899', 'hash656', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Michelle', 'Gamboa', 'Ortiz', 'michelle@correo.com', '8767-8899', 'hash956', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Pablo', 'Zuniga', 'Salas', 'pabloz@correo.com', '8768-8899', 'hash156', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Gustavo', 'Rojas', 'Sanchez', 'gustavo@correo.com', '8769-8899', 'hash256', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Miguel', 'Rodriguez', 'Diaz', 'miguel@correo.com', '8771-8699', 'hash556', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Brandon', 'Fuentes', 'Calvo', 'brandon@correo.com', '8772-8691', 'hash654', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Sophia', 'Vargas', 'Torres', 'sophia@correo.com', '8772-8692', 'hash0543', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Andres', 'Mata', 'Faerron', 'andres@correo.com', '8773-8693', 'hash943', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Kimberly', 'Vargas', 'Chavarria', 'kimberly@correo.com', '8774-8694', 'hash643', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Sergio', 'Montenegro', 'Aguilar', 'sergio@correo.com', '8773-4444', 'hash344', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Nathalia', 'Pinar', 'Cruz', 'nathalia@correo.com', '7017-8694', 'hash888', 2);
INSERT INTO USUARIOS (NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, CONTRASENA_HASH, ID_ROL) VALUES ('Kattia', 'Cruz', 'Cruz', 'kattia@correo.com', '7017-3250', 'hash701', 2);

INSERT INTO TIPO_SALA (DESCRIPCION_TIPO) VALUES ('Sala de reuniones');
INSERT INTO TIPO_SALA (DESCRIPCION_TIPO) VALUES ('Oficina privada');
INSERT INTO TIPO_SALA (DESCRIPCION_TIPO) VALUES ('Sala de capacitacion');

INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO)
VALUES ('Sala A', 10, 15000, 1, 1);

INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO)
VALUES ('Sala B', 4, 10000, 2, 2);

INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO)
VALUES ('Sala C', 20, 25000, 3, 3);

INSERT INTO ESTADOS (NOMBRE_ESTADO) VALUES ('Pendiente');
INSERT INTO ESTADOS (NOMBRE_ESTADO) VALUES ('Confirmada');
INSERT INTO ESTADOS (NOMBRE_ESTADO) VALUES ('Cancelada');
INSERT INTO ESTADOS (NOMBRE_ESTADO) VALUES ('Finalizada');

INSERT INTO RESERVAS (ID_USUARIO, ID_SALA, ID_ESTADO, FECHA, HORA_INICIO, HORA_FIN, COSTO_TOTAL)
VALUES (
    2,
    1,
    2,
    DATE '2026-03-15',
    TO_TIMESTAMP('2026-03-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-03-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    30000
);

INSERT INTO RESERVAS (ID_USUARIO, ID_SALA, ID_ESTADO, FECHA, HORA_INICIO, HORA_FIN, COSTO_TOTAL)
VALUES (
    2,
    2,
    1,
    DATE '2026-03-16',
    TO_TIMESTAMP('2026-03-16 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-03-16 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    20000
);

INSERT INTO SERVICIOS (NOMBRE_SERVICIO, PRECIO_ADICIONAL) VALUES ('Proyector', 5000);
INSERT INTO SERVICIOS (NOMBRE_SERVICIO, PRECIO_ADICIONAL) VALUES ('Coffee Break', 8000);
INSERT INTO SERVICIOS (NOMBRE_SERVICIO, PRECIO_ADICIONAL) VALUES ('Pizarra', 3000);

INSERT INTO RESERVA_SERVICIOS (ID_RESERVA, ID_SERVICIO, CANTIDAD) VALUES (1, 1, 1);
INSERT INTO RESERVA_SERVICIOS (ID_RESERVA, ID_SERVICIO, CANTIDAD) VALUES (1, 2, 1);
INSERT INTO RESERVA_SERVICIOS (ID_RESERVA, ID_SERVICIO, CANTIDAD) VALUES (2, 3, 1);

INSERT INTO PAGOS (ID_RESERVA, MONTO_TOTAL, METODO_PAGO) VALUES (1, 43000, 'Tarjeta');
INSERT INTO PAGOS (ID_RESERVA, MONTO_TOTAL, METODO_PAGO) VALUES (2, 23000, 'SINPE');

INSERT INTO BITACORA_CAMBIOS (ID_RESERVA, ID_ESTADO_ANTERIOR, ID_ESTADO_NUEVO)
VALUES (1, 1, 2);

INSERT INTO BITACORA_CAMBIOS (ID_RESERVA, ID_ESTADO_ANTERIOR, ID_ESTADO_NUEVO)
VALUES (2, 1, 3);

COMMIT;

-- ============================================
-- VERIFICACIÓN
-- ============================================
SELECT table_name
FROM user_tables
ORDER BY table_name;



SELECT COUNT(*) FROM EDIFICIO;
SELECT COUNT(*) FROM PISO;
SELECT COUNT(*) FROM ROLES;
SELECT COUNT(*) FROM USUARIOS;


SELECT * FROM EDIFICIO;

SELECT * FROM EDIFICIO FETCH FIRST 10 ROWS ONLY;

SELECT 'EDIFICIO' AS TABLA, COUNT(*) AS TOTAL FROM EDIFICIO
UNION ALL
SELECT 'PISO', COUNT(*) FROM PISO
UNION ALL
SELECT 'ROLES', COUNT(*) FROM ROLES
UNION ALL
SELECT 'USUARIOS', COUNT(*) FROM USUARIOS;

SHOW USER;

SELECT * FROM EDIFICIO;
SELECT * FROM PISO;
SELECT * FROM ROLES;
SELECT * FROM USUARIOS;

--Cambio formato horas de reserva ajuste 

DESC COWORKINGDB.RESERVAS;


ALTER TABLE COWORKINGDB.RESERVAS ADD HORA_INICIO_TXT VARCHAR2(5);
ALTER TABLE COWORKINGDB.RESERVAS ADD HORA_FIN_TXT VARCHAR2(5);

UPDATE COWORKINGDB.RESERVAS
SET HORA_INICIO_TXT = TO_CHAR(HORA_INICIO, 'HH24:MI'),
    HORA_FIN_TXT    = TO_CHAR(HORA_FIN, 'HH24:MI');

    SELECT ID_RESERVA, HORA_INICIO, HORA_INICIO_TXT, HORA_FIN, HORA_FIN_TXT
FROM COWORKINGDB.RESERVAS;

ALTER TABLE COWORKINGDB.RESERVAS RENAME COLUMN HORA_INICIO_TXT TO HORA_INICIO;
ALTER TABLE COWORKINGDB.RESERVAS RENAME COLUMN HORA_FIN_TXT TO HORA_FIN;

ALTER TABLE COWORKINGDB.RESERVAS DROP COLUMN HORA_INICIO;

ALTER TABLE COWORKINGDB.RESERVAS DROP COLUMN HORA_FIN;

ALTER TABLE COWORKINGDB.RESERVAS RENAME COLUMN HORA_INICIO_TXT TO HORA_INICIO;

ALTER TABLE COWORKINGDB.RESERVAS RENAME COLUMN HORA_FIN_TXT TO HORA_FIN;

DESC COWORKINGDB.RESERVAS;

DELETE FROM SALAS;
COMMIT;

INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('San José', 10, 15000, 1, 1);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Heredia', 8, 12000, 1, 1);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Alajuela', 12, 18000, 1, 2);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Cartago', 6, 10000, 2, 2);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Liberia', 15, 20000, 1, 3);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Puntarenas', 5, 9000, 2, 3);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Limón', 7, 11000, 2, 1);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Escazú', 10, 16000, 1, 2);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Santa Ana', 9, 14000, 1, 2);
INSERT INTO SALAS (NOMBRE_SALA, CAPACIDAD, PRECIO_HORA, ID_TIPO, ID_PISO) VALUES ('Pérez Zeledón', 8, 13000, 2, 3);

COMMIT;

SELECT DISTINCT NOMBRE_SALA, ID_SALA
FROM SALAS
ORDER BY NOMBRE_SALA

DELETE FROM SALAS;
COMMIT;


--Cursores

-- Ver la lista de reservas
CREATE OR REPLACE PROCEDURE SP_LISTA_RESERVAS_CURSOR
IS
    CURSOR C_RESERVAS IS
        SELECT 
            R.ID_RESERVA,
            U.NOMBRE || ' ' || U.APELLIDO_1 || ' ' || U.APELLIDO_2 AS USUARIO,
            S.NOMBRE_SALA,
            E.NOMBRE_ESTADO,
            R.FECHA,
            R.HORA_INICIO,
            R.HORA_FIN,
            NVL(P.MONTO_TOTAL, 0) AS MONTO_PAGADO
        FROM RESERVAS R
        INNER JOIN USUARIOS U ON R.ID_USUARIO = U.ID_USUARIO
        INNER JOIN SALAS S ON R.ID_SALA = S.ID_SALA
        INNER JOIN ESTADOS E ON R.ID_ESTADO = E.ID_ESTADO
        LEFT JOIN PAGOS P ON R.ID_RESERVA = P.ID_RESERVA
        ORDER BY R.ID_RESERVA;

    V_ID_RESERVA    RESERVAS.ID_RESERVA%TYPE;
    V_USUARIO       VARCHAR2(300);
    V_NOMBRE_SALA   SALAS.NOMBRE_SALA%TYPE;
    V_ESTADO        ESTADOS.NOMBRE_ESTADO%TYPE;
    V_FECHA         RESERVAS.FECHA%TYPE;
    V_HORA_INICIO   RESERVAS.HORA_INICIO%TYPE;
    V_HORA_FIN      RESERVAS.HORA_FIN%TYPE;
    V_MONTO_PAGADO  NUMBER(10,2);

BEGIN
    OPEN C_RESERVAS;
    LOOP
        FETCH C_RESERVAS INTO 
            V_ID_RESERVA,
            V_USUARIO,
            V_NOMBRE_SALA,
            V_ESTADO,
            V_FECHA,
            V_HORA_INICIO,
            V_HORA_FIN,
            V_MONTO_PAGADO;

        EXIT WHEN C_RESERVAS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('------------------------------');
        DBMS_OUTPUT.PUT_LINE('ID Reserva: ' || V_ID_RESERVA);
        DBMS_OUTPUT.PUT_LINE('Usuario: ' || V_USUARIO);
        DBMS_OUTPUT.PUT_LINE('Sala: ' || V_NOMBRE_SALA);
        DBMS_OUTPUT.PUT_LINE('Estado: ' || V_ESTADO);
        DBMS_OUTPUT.PUT_LINE('Fecha: ' || TO_CHAR(V_FECHA, 'DD/MM/YYYY'));
        DBMS_OUTPUT.PUT_LINE('Hora inicio: ' || V_HORA_INICIO);
        DBMS_OUTPUT.PUT_LINE('Hora fin: ' || V_HORA_FIN);
        DBMS_OUTPUT.PUT_LINE('Monto pagado: ' || V_MONTO_PAGADO);
    END LOOP;
    CLOSE C_RESERVAS;
END;
/

SET SERVEROUTPUT ON;
EXEC SP_LISTA_RESERVAS_CURSOR;


------ Ver lista de salas disponibles

CREATE OR REPLACE PROCEDURE SP_LISTA_SALAS_DISPONIBLES
IS
    CURSOR C_SALAS IS
        SELECT ID_SALA, NOMBRE_SALA, CAPACIDAD, PRECIO_HORA
        FROM SALAS
        WHERE ID_SALA NOT IN (
            SELECT ID_SALA
            FROM RESERVAS
        )
        ORDER BY NOMBRE_SALA;

    V_ID_SALA      SALAS.ID_SALA%TYPE;
    V_NOMBRE_SALA  SALAS.NOMBRE_SALA%TYPE;
    V_CAPACIDAD    SALAS.CAPACIDAD%TYPE;
    V_PRECIO_HORA  SALAS.PRECIO_HORA%TYPE;

BEGIN
    OPEN C_SALAS;

    LOOP
        FETCH C_SALAS INTO V_ID_SALA, V_NOMBRE_SALA, V_CAPACIDAD, V_PRECIO_HORA;

        EXIT WHEN C_SALAS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('----------------------');
        DBMS_OUTPUT.PUT_LINE('Sala: ' || V_NOMBRE_SALA);
        DBMS_OUTPUT.PUT_LINE('Capacidad: ' || V_CAPACIDAD);
        DBMS_OUTPUT.PUT_LINE('Precio por hora: ' || V_PRECIO_HORA);
    END LOOP;

    CLOSE C_SALAS;
END;
/


SET SERVEROUTPUT ON;
EXEC SP_LISTA_SALAS_DISPONIBLES;

--TRIGGERS

CREATE OR REPLACE TRIGGER TRG_EVITAR_OVERBOOKING
BEFORE INSERT ON RESERVAS
FOR EACH ROW
DECLARE
    v_conteo NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_conteo
    FROM RESERVAS
    WHERE ID_SALA = :NEW.ID_SALA
      AND FECHA = :NEW.FECHA
      AND ID_ESTADO IN (1, 2) -- Si esta pendiente o confirmada
      AND (
          (:NEW.HORA_INICIO < HORA_FIN AND :NEW.HORA_FIN > HORA_INICIO)
      );

    IF v_conteo > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error: La sala ya se encuentra reservada en la fecha y hora seleccionadas.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_CORREO_USUARIO
BEFORE INSERT OR UPDATE ON USUARIOS
FOR EACH ROW
BEGIN

    IF NOT REGEXP_LIKE(:NEW.CORREO, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE_APPLICATION_ERROR(-20002, 'El Formato del correo no es valido.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CALCULAR_COSTO_RESERVA
BEFORE INSERT OR UPDATE OF HORA_INICIO, HORA_FIN ON RESERVAS
FOR EACH ROW
DECLARE
    v_precio_hora NUMBER(10,2);
    v_horas NUMBER;
BEGIN
    -- Obtiene el precio de la sala seleccionada
    SELECT PRECIO_HORA INTO v_precio_hora 
    FROM SALAS WHERE ID_SALA = :NEW.ID_SALA;

    -- Calcula la diferencia en horas aqui y extrae la diferencia y lo multiplica por 24 para tener horas decimales
    v_horas := EXTRACT(HOUR FROM (:NEW.HORA_FIN - :NEW.HORA_INICIO)) + 
               (EXTRACT(MINUTE FROM (:NEW.HORA_FIN - :NEW.HORA_INICIO)) / 60);

    :NEW.COSTO_TOTAL := v_horas * v_precio_hora;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_ESTADOS
AFTER UPDATE OF ID_ESTADO ON RESERVAS
FOR EACH ROW
BEGIN
    -- Inserta si el estado cambio
    IF :OLD.ID_ESTADO != :NEW.ID_ESTADO THEN
        INSERT INTO BITACORA_CAMBIOS (
            ID_RESERVA, 
            ID_ESTADO_ANTERIOR, 
            ID_ESTADO_NUEVO, 
            FECHA_CAMBIO
        ) VALUES (
            :NEW.ID_RESERVA, 
            :OLD.ID_ESTADO, 
            :NEW.ID_ESTADO, 
            SYSTIMESTAMP
        );
    END IF;
END;
/