/* ------------------------------------------------------
   UNIVERSIDAD FIDÉLITAS
   CURSO: LENGUAJE DE BASE DE DATOS
   PROYECTO: Sistema de Gestión de Espacios de Coworking
   ENTREGABLE: Avance Final
------------------------------------------------------ */

-- ============================================
-- SCRIPT ADMIN
-- Crear y habilitar el usuario del proyecto
-- ===========================================

ALTER USER COWORKINGDB IDENTIFIED BY "Password123*";
ALTER USER COWORKINGDB ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO COWORKINGDB;
ALTER USER COWORKINGDB QUOTA UNLIMITED ON USERS;

SELECT USER FROM DUAL;
--------------------------------------------------------
-- BLOQUE OPCIONAL: BORRAR TODO DESDE CERO
-- Ejecutar solo si deseas reiniciar completamente
--------------------------------------------------------
DROP TABLE BITACORA_CAMBIOS CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE RESERVA_SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE ESTADOS CASCADE CONSTRAINTS;
DROP TABLE SALAS CASCADE CONSTRAINTS;
DROP TABLE TIPO_SALA CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ROLES CASCADE CONSTRAINTS;
DROP TABLE PISO CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO CASCADE CONSTRAINTS;

